### ISSUE TITLE
[Question]: Run without plugin

### ISSUE THREAD

**Issue by setoff** [reaster/schema-gen#12]
Hello!

I've encountered issue described here https://github.com/reaster/schema-gen/issues/10 but with different scheme. I ran schema-gen with gradle plugin. As far as I understand the problem has been fixed but I need to run schema-gen "directly" (since plugin is not supported any more).

I'm not familiar with groovy, gradle etc. Could you please elaborate what does it mean "The main entry point is com.javagen.schema.swift.SwiftGen which **can be invoked directly**"?

What tools I need to install?
How to build schema-gen itself?
How run schema-gen without gradle plugin?

**Comment by reaster** [comment]
schema-gen can be built using Gradle command: 

`gradle build`

However, that doesn't buy you much because you still need to tweak the config and sometimes the schema and/or the framework itself to get the desired result. I recommend using the Community edition of [IntelliJ](https://www.jetbrains.com/idea/download/) because it has good support for both Groovy and Gradle. You can import the build.gradle file and IntelliJ will download the dependencies and compile the framework. Then, you can start playing with the examples found in [DartGenMain.groovy](https://github.com/reaster/schema-gen/blob/master/src/main/groovy/com/javagen/schema/dart/DartGenMain.groovy), [SwiftGenMain.groovy](https://github.com/reaster/schema-gen/blob/master/src/main/groovy/com/javagen/schema/swift/SwiftGenMain.groovy), etc. to exercise the code generator. 

The companion [schema-gen-examples](https://github.com/reaster/schema-gen-examples) project demonstrates how to test and use the generated code. If you install the examples project in the same parent folder as schema-gen, you can re-generate the existing examples using the above mentioned \<language\>GenMain.groovy files which can serve as working templates for your own project. 

If you have a simple, well designed schema, with luck you may get a working code set without much effort. However, most real world schemas will require delving into the framework which can be a steep learning curve, especially if you don't know Groovy. Also, all these tools and languages are moving targets, which is why the groovy plugin broke and why current java/groovy version support is lacking. These will eventually be addressed, but you may have to wait until I have a personal or commercial requirenment or a contributor issues a pull request.

**Comment by setoff** [comment]
Thank you for response and advices!
