### ISSUE TITLE
Sample for Kotlin/JS?

### ISSUE THREAD

**Issue by joerg-rade** [reaster/schema-gen#9]
Hi Richard,
I would like to use schema-gen for a Kotlin/JS project.
Do you know of any projects/samples?

Thanks in advance 
-j

**Comment by reaster** [comment]
Kotlin support is about 85% baked and I don't anticipate doing any more work on it because I'm all in on Flutter/Dart these days. So depending on your schema and the style of code you want, it may or may not work. The primary Kotlin example is here:

https://github.com/reaster/schema-gen-examples/blob/master/kotlin-gpx/src/main/kotlin-gen/Gpx.kt
https://github.com/reaster/schema-gen-examples/blob/master/kotlin-gpx/src/test/kotlin/GpxTest.kt

The Gradle plugin is currently not working so you'll want to use KotlinGenMain to generate your code:

https://github.com/reaster/schema-gen/blob/master/src/main/groovy/com/javagen/schema/kotlin/KotlinGenMain.groovy
